- job:
    name: PROJECT-setup
    description: "This job step checks out the branch and builds the tarballs, diffs, and dsc that are passed to the PROJECT-build step.\r\n\r\nNotes:\r\nJob needs to run on a releatively recent debian system.  The Restrict where run feature is used to specifiy an appropriate label.\r\nThe clear workspace before checkout box for the git plugin is used."
    # we do not need to pin this to trusty anymore for the new jenkins instance
    # FIXME: unpin when this gets ported over
    node: small && trusty
    display-name: 'PROJECT-setup'
    logrotate:
      daysToKeep: -1
      numToKeep: 25
      artifactDaysToKeep: -1
      artifactNumToKeep: -1
    block-downstream: false
    block-upstream: false
    concurrent: true
    properties:
      - github:
          url: https://github.com/ceph/GITHUB

    parameters:
      - string:
          name: BRANCH
          description: "The git branch (or tag) to build"

    scm:
      - git:
          url: git@github.com:ceph/GITHUB.git
          # Use the SSH key attached to the ceph-jenkins GitHub account.
          credentials-id: '39fa150b-b2a1-416e-b334-29a9a2c0b32d'
          branches:
            - $BRANCH
          skip-tag: true
          wipe-workspace: true

    builders:
      - shell:
          !include-raw ../../build/build

    publishers:
      - archive:
          artifacts: 'dist/**'
          allow-empty: false
          latest-only: false

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
