- job:
    name: PROJECT-build
    project-type: matrix
    defaults: global
    display-name: 'PROJECT-build'
    block-downstream: false
    block-upstream: false
    concurrent: true
    properties:
      - github:
          url: https://github.com/ceph/GITHUB
    execution-strategy:
       combination-filter: DIST==AVAILABLE_DIST && ARCH==AVAILABLE_ARCH && (ARCH=="x86_64" || (ARCH == "arm64" && (DIST == "xenial" || DIST == "centos7")))
    axes:
      - axis:
          type: label-expression
          name: MACHINE_SIZE
          values:
            - small
      - axis:
          type: label-expression
          name: AVAILABLE_ARCH
          values:
            - x86_64
            - arm64
      - axis:
          type: label-expression
          name: AVAILABLE_DIST
          values:
            - centos6
            - centos7
            - trusty
            - xenial
            - jessie
            - precise
            - wheezy
      - axis:
          type: dynamic
          name: DIST
      - axis:
          type: dynamic
          name: DIST
          values:
            - DISTROS
      - axis:
          type: dynamic
          name: ARCH
          values:
            - ARCHS



    builders:
      - shell: |
          echo "Cleaning up top-level workarea (shared among workspaces)"
          rm -rf dist
          rm -rf venv
          rm -rf release
      - copyartifact:
          project: PROJECT-setup
          filter: 'dist/**'
          which-build: last-successful
      - inject:
          properties-file: ${WORKSPACE}/dist/inject
      # debian build scripts
      - shell:
          !include-raw:
            - ../../build/validate_deb
            - ../../../scripts/build_utils.sh
            - ../../build/setup
            - ../../build/setup_pbuilder
            - ../../build/build_deb
      # rpm build scripts
      - shell:
          !include-raw:
            - ../../build/validate_rpm
            - ../../../scripts/build_utils.sh
            - ../../build/setup
            - ../../build/build_rpm

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
